### ISSUE TITLE
User test de voorhoede

### ISSUE THREAD

**Issue by Nazneen05x** [Ryank2004/the-startup-responsive-interactieve-website#16]
## User test de voorhoede:

Je moet je scenario vraag veranderen naar een vraagvorm, je legt nu de stappen uit die ik moet uitvoeren. We hebben al samen gebrainstormd hoe we deze “stappenplan vraag” kunnen omzetten naar een vraag scenario.

Verbetering:
Goed je vraag scenario verbetert!

## Code

Je pagina ziet er mooi uit! heel leuk die animaties! 

Ik zou je script in je head zetten en dan ernaast Defer

 `<script src="script.js"></script>  `

Hier een artikel over wat defer betekent:

https://www.marketingtracer.com/nl/seo/verbeter-website-snelheid-defer-javascript
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

**Comment by Ryank2004** [comment]
Thanks! Goeie tip van de JS. Gelijkt aangepast.
